### ISSUE TITLE
4.0.0 release checklist

### ISSUE THREAD

**Issue by benoit-pierre** [openstenoproject/plover#1206]
Pre:

- [x] put Circle CI out of its misery: it will continue trying and failing even though the configuration has been removed...
- [x] update translations (French, Spanish) (for #1165 post release)
- [x] clarify macOS situation: oldest supported version?
- [x] configure PyPI token for release
- [x] update to Python 3.8
- [x] update requirements (taking the macOS situation into account, should address #1183 and #1192)
- [x] review and merge #1153
- [x] review and merge #1149 / #1244 (Save As… feature)
- [x] add Calibre-like warning to plugins manager
- [x] do a pass on setup metadata (changelog link? switch back long description to readme contents?)
- [x] clear 4.0.0 milestone: #904 (libusb), #912 (plugin docs), ~~and #1180 (extensions config)~~ still left
- [ ] create a RC for testing, promote to final when happy
- [x] update AUR (git) package

Post RC/final:
- [ ] update AUR (stable) package
- [x] add Melani plugin to registry (need new version to depend on)
- [ ] add Yawei-Steno3 plugin to registry

Possibly:
- [x] ~update other Linux distributions packages~
- [x] partially merge #999 (punctuation consistency only)
- [x] review and merge #1163 (lock display)
- [x] cherry pick part of #1092
- [x] redesign icon for Big Sur (add dumb white box around it)
- [x] #1067 (register AppImage)

**Comment by benoit-pierre** [comment]
@morinted: thoughts? Anything I missed?
