### ISSUE TITLE
Sign releases

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#910]
## Summary

We should sign Plover releases to avoid untrusted warnings on Windows and Mac.

- [ ] Windows
- [ ] Mac
- [ ] Linux (optional)

## Tasks

- [ ] Purchase Windows code-signing license
- [ ] Sign installer
- [ ] Add to CI

- [ ] Purchase Apple Developer License
- [ ] Sign bundle
- [ ] Add to CI

**Comment by wcarhart** [comment]
Is there any movement on or plan for this issue? I know these licenses are not free - is there a monthly sponsoring minimum needed to enable this? Unfortunately the lack of signing prevents me from using Plover in work environments :(
